# Using latest release of Atlantis
ARG version=latest
FROM ghcr.io/runatlantis/atlantis:${version}

# Copy the built local binary of infracost - note this needs to happen before running docker-compose up
ADD infracost /usr/local/bin/infracost

# Install required packages
RUN apk --update --no-cache add ca-certificates openssl openssh-client curl git jq

WORKDIR /atlantis/src
